// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package wire

import (
	"github.com/jinzhu/gorm"
	"sme-scaffold/internal/domain/base"
	"sme-scaffold/internal/domain/product"
)

// Injectors from wire.go:

// InitBaseAPI init base api wire
func InitBaseAPI() base.API {
	service := base.ProvideService()
	api := base.ProvideAPI(service)
	return api
}

// InitBaseAPI init base api wire
func InitProductAPI(db *gorm.DB) product.API {
	repository := product.ProvideRepository(db)
	service := product.ProvideService(repository)
	api := product.ProvideAPI(service)
	return api
}
