
################################################################
######
######    base section
######
################################################################

### release
# 返回：
GET http://127.0.0.1:11911/release
Content-Type: application/x-www-form-urlencoded